version: "3"

services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=user
      - POSTGRES_DB=time_tracker
      - TZ=UTC
    ports:
      - "5432:5432"
